### PR TITLE
New style with bulma

### PR DESCRIPTION
**Pull request by PanRada**
new style with bulma

### CODE REVIEW

**Comment by PanRada** [comment]
zamykam wymaga lekkich poprawek

**Comment by piotrwitek** [comment]
ok spoko, robiles rebase z mojego repo czy merge? bo nie widze swoich commitow tylko Twoje z moimi zmianami, więc to wyglada jak merge i przez to zgubiles historię, musisz pamietac przy pull zeby uzywac rebase :)

**Comment by PanRada** [comment]
:( no to namieszalem jeszcze robie poprawki bo ten textarea jest bardzo
 upierdliwe

2016-06-18 11:16 GMT+02:00 Piotr Witek notifications@github.com:

**Comment by piotrwitek** [comment]
Spoko podaje instrukcje i dodaje do Tipsow w readme bo jak ktos nie robil nigdy to mozna sie pogubic :)

# Add the remote, call it "upstream":

git remote add upstream https://github.com/whoever/whatever.git

# Fetch all the branches of that remote into remote-tracking branches,

# such as upstream/master:

git fetch upstream

# Make sure that you're on your master branch:

git checkout master

# Rewrite your master branch so that any commits of yours that

# aren't already in upstream/master are replayed on top of that

# other branch:

git rebase upstream/master

**Comment by piotrwitek** [comment]
http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Pull request closed without merging**
